### ISSUE TITLE
Line breaks should not the removed

### ISSUE THREAD

**Issue by gabriel-r** [AWtnb/vscode-smart-title-case#2]
I'm seeing this issue when working with a Table of Contents, e.g. 

````
1. Quick start
  1.1 Getting access to the environment 
  1.2 Security implications 
2. Create and mange collectables
  2.1 Create your first collectable
  2.2 Update and transaction collectable status
````

…will result in `1. Quick Start 1.1 Getting Access to the Environment 1.2 Security Implications 2. Create and Mange Collectables 2.1 Create Your First Collectable 2.2 Update and Transaction Collectable Status`

**When converting multiple lines of text, line breaks should be preserved.** 

FWIS, the built-in dumb "Transform to Title Case" preserved line breaks as expected.

**Comment by AWtnb** [comment]
Thanks for reporting Issure!

I hadn't thought about multi-line cases. But it is indeed a necessary feature in actual usage scenarios.
I will fix it. I'm wondering how to format selection while keeping the indentation of each line...🤔

**Comment by gabriel-r** [comment]
You can tread words or word groups individually. Word groups should break at line breaks too.

**Comment by AWtnb** [comment]
Updated: v0.3.0 should now support multi-line formatting.

This extension also reduce consecutive whitespace to a single whitespace (e.g. `a  b` to `a b`). Therefore, it was necessary to separate the indentation part from the character part.

[This commit](https://github.com/AWtnb/vscode-smart-title-case/commit/a0fde084f460a1554eb3872f89550b4a67496ab9) should handle line breaks as expected, even if they are included. Great learning experience!
